package a40Exception_Handling;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

/*
 * 
 */

public class fException_by_throws {

	public static void main(String[] args) throws FileNotFoundException {
		
		System.out.println("Program Execution Started");
		
		int a = 10;
		int b = 0;		
		int result = 0;
		
		File file = new File("D:/resume.docx");
		FileInputStream fis = new FileInputStream(file);
		
		try {
			result = a / b;
		}catch(ArithmeticException ae) {
			System.out.println(ae.toString());
			
			throw ae;
		}
		finally {
			System.out.println("Finally block");
		}
	
		
		System.out.println("Output is : " +result);
		
		System.out.println("Program Execution Ended");
	}


}
