package a40Exception_Handling;

public class cException_by_try_catch_block {

	public static void main(String[] args) {

		int a = 10;
		int b = 0;
		
		int result = 0;
		
		result = a / b;
	
		System.out.println(result);
	}


}
